/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Move
{
    public class Num : Message
    {
        public const string RosMessageName = "move/Num";

        public long num2 { get; set; }
        public long num { get; set; }

        public Num()
        {
            this.num2 = 0;
            this.num = 0;
        }

        public Num(long num2, long num)
        {
            this.num2 = num2;
            this.num = num;
        }
    }
}
